version: '3.8'

services:
  frontend:
    build:
      context: ./front-end/tg-app-shop
      dockerfile: Dockerfile
    container_name: tg_shop_frontend
    ports:
      - "3478:3478"
  
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./beack-end
      dockerfile: Dockerfile
    container_name: tg_shop_backend
    ports:
      - "7770:7770"
    
    depends_on:
      - postgres
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:14.15
    container_name: tg_shop_db
   
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
 
    depends_on:
      - backend
    networks:
      - app-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge 