services:
  database:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=G21nd21nd1opsa
      - POSTGRES_DB=tg_shop
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  back-end:
    container_name: tg_shop_back_end 
    build:
      context: .
      dockerfile: Dockerfile
      target: final-backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=G21nd21nd1opsa
      - POSTGRES_DB=tg_shop
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://postgres:G21nd21nd1opsa@database:5432/tg_shop
      - TG_ADMINS=36194498|Admin1,36194499|Admin2,1071973201|Admin3
      - DELETE_DATABASE=False
    ports:
      - "8080:8080" 
    depends_on:
      database:
        condition: service_healthy
    restart: always
    networks:
      - app_network

  bot:
    container_name: tg_shop_bot
    build:
      context: .
      dockerfile: Dockerfile
      target: final-bot
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

