version: "3.9"


services:
  front-end:
    container_name: tg_shop_front_end
    build: ./front-end/tg-app-shop
    env_file:
      - ./front-end/tg-app-shop/.env
    ports:
      - "3478:3478"
    networks:
      - app-network


  # Когда фронтенд успешно задеплоится, можно будет добавить бота:
  # bot:
  #   build:
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   container_name: tg_shop_bot
  #   networks:
  #     - app-network
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

networks:
  app-network:
    driver: bridge 