version: "3.9"

services:
  front-end:
    build: ./front-end/tg-app-shop
    container_name: tg_shop_app
    env_file:
      - ./front-end/tg-app-shop/.env
    ports:
      - "8000:8000"

  back-end:
    container_name: tg_shop_back_end
    build: ./back-end/
    env_file:
      - ./back-end/.env
    ports:
      - "7770:7770" 
    depends_on:
        - database


  database:
    image: postgres:15
    container_name: database
    env_file:
      - ./back-end/.env
    ports:
      - "5432:5432"

  bot:
    container_name: tg_shop_bot
    build: ./bot
    env_file:
      - ./bot/.env


  # Когда фронтенд успешно задеплоится, можно будет добавить бота:
  # bot:
  #   build:
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   container_name: tg_shop_bot
  #   networks:
  #     - app-network
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

