version: "3.9"


services:
  app:
    container_name: tg_shop_app
    build: ./front-end/tg-app-shop/Dockerfile
    env_file:
      - ./front-end/tg-app-shop/.env
    ports:
      - "3478:3478"
    environment:
      - VITE_API_BASE_URL=http://localhost:7770
      - VITE_STATIC_URL=http://localhost:7770

  #back-end:
  #  container_name: tg_shop_back_end
  #  build: ./back-end/
  #  env_file:
  #    - ./back-end/.env
  #  networks:
  #    - app-network

  #ports:
  #  - "7770:7770" 

  #bot:
  #  container_name: tg_shop_bot
  #  build: ./bot
  #  env_file:
  #    - ./bot/.env
  #  networks:
  #    - app-network

  # Когда фронтенд успешно задеплоится, можно будет добавить бота:
  # bot:
  #   build:
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   container_name: tg_shop_bot
  #   networks:
  #     - app-network
  #   restart: always
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

networks:
  app-network:
    driver: bridge 