FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Установка express для продакшн-сервера
RUN npm install express

EXPOSE 3478

CMD ["node", "server.js"] 